/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as ProjectsIndexImport } from './pages/projects/index'
import { Route as ProjectsProjectCardImport } from './pages/projects/-ProjectCard'
import { Route as ProjectsProjectsTestImport } from './pages/projects/Projects.test'

// Create/Update Routes

const ProjectsIndexRoute = ProjectsIndexImport.update({
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectCardRoute = ProjectsProjectCardImport.update({
  path: '/projects/ProjectCard',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectsTestRoute = ProjectsProjectsTestImport.update({
  path: '/projects/projects/test',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects/ProjectCard': {
      preLoaderRoute: typeof ProjectsProjectCardImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/projects/test': {
      preLoaderRoute: typeof ProjectsProjectsTestImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  ProjectsProjectCardRoute,
  ProjectsIndexRoute,
  ProjectsProjectsTestRoute,
])

/* prettier-ignore-end */
